site:
  title: Feel++ ShapO // Docs
  url: https://feelpp.github.io/feelpp-shapo
  start_page: shapo:ROOT:index.adoc
content:
  sources:
  - url: https://github.com/feelpp/feelpp-shapo
    branches: master
    start_path: docs
ui:
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip 
    snapshot: true
output:
  clean: true
  dir: public
  
asciidoc:
  attributes:
    project_version: 0.109
    deploymentRoot: ""
    numbered: true
    allow-uri-read: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    swimmer: Swimmer
